### ISSUE TITLE
Tests for align

### ISSUE THREAD

**Issue by TobiasHeOl** [xchem/fragalysis-api#26]
Tests for the new additions needs to be added

**Comment by martinjrobins** [comment]
Thanks @TobiasHeOl. My suggestions for a possible workflow would be:

1. Someone assign themselves (or be assigned) to this issue
2. Create a branch, e.g. `issue-26-test-align`
3. Assigned person work on this branch, adding commits with messages like `"#26 this commit does this wonderful and amazing thing"`, so that github adds them to this issue
4. When finished, assigned person creates a pull request to master, which must be reviewed by at least one other person before being merged into master

You might want to adjust this for your team preferences, but this should give you a good workflow to start with.
